---
permalink: online-help/concept_network_interface_performance_explorer_page.html
sidebar: sidebar
keywords: 
summary: 'The Network Interface/Performance Explorer page provides a detailed performance overview for all of the network interfaces \(LIFs\) within a cluster.'
---
= Network Interface/Performance Explorer page
:icons: font
:imagesdir: ../media/

[.lead]
The Network Interface/Performance Explorer page provides a detailed performance overview for all of the network interfaces (LIFs) within a cluster.

The Network Interface/Performance Explorer page enables you to track and compare network interface performance during a specific time period, which helps you to troubleshoot and fine-tune your network interface performance.

Using the View and Compare functionality you can compare the performance of this network interface with:

* other network interfaces that are on the same port
* other network interfaces that are on the same storage VM
* the port on which the network interface resides
* the storage VM on which the network interface resides

The Network Interface/Performance Explorer page enables you to:

* View threshold-related issues and their details
* Track and compare network interface performance data
* Investigate and troubleshoot threshold-related issues
* Investigate and troubleshoot performance issues

*Related information*

xref:concept_components_of_the_performance_explorer_page.adoc[Components of the Performance Explorer page]

xref:reference_summary_page_opm.adoc[Summary page]

xref:task_defining_the_list_of_correlated_objects_for_comparison_graphing.adoc[Defining the list of correlated objects for comparison graphing]

xref:reference_types_of_performance_counter_charts.adoc[Types of performance counter charts]

xref:task_selecting_performance_charts_to_display.adoc[Selecting performance charts to display]

xref:concept_counter_charts_zoom_view.adoc[Counter Charts Zoom View]
