---
permalink: online-help/concept-cluster-performance-explorer-page.html
sidebar: sidebar
keywords: 
summary: 'The Cluster/Performance Explorer page provides a detailed performance overview of all the clusters that are managed by Unified Manager.'
---
= Cluster/Performance Explorer page
:icons: font
:imagesdir: ../media/

[.lead]
The Cluster/Performance Explorer page provides a detailed performance overview of all the clusters that are managed by Unified Manager.

The Cluster/Performance Explorer page enables you to track cluster performance and compare the objects within that cluster during a specific time period, which helps in troubleshooting and fine-tuning the performance of a cluster.

Using the View and Compare functionality you can compare the performance of the cluster with:

* the nodes on this cluster
* the storage VMs of this cluster
* the aggregates on this cluster

The Cluster/Performance Explorer page enables you to:

* View threshold-related issues and their details
* Track cluster performance data
* Investigate and troubleshoot threshold-related issues
* Investigate and troubleshoot performance issues
