---
permalink: online-help/reference_performance_all_ports_view.html
sidebar: sidebar
keywords: 
summary: 'The Performance: All Ports view displays an overview of the performance events, data, and configuration information for each port that is being monitored by an instance of Unified Manager. This enables you to quickly monitor the performance of your ports, and to troubleshoot performance issues and threshold events.'
---
= Performance: All Ports view
:icons: font
:imagesdir: ../media/

[.lead]
The Performance: All Ports view displays an overview of the performance events, data, and configuration information for each port that is being monitored by an instance of Unified Manager. This enables you to quickly monitor the performance of your ports, and to troubleshoot performance issues and threshold events.

[NOTE]
====
Performance counter values are displayed for physical ports only. Counter values are not displayed for VLANs or interface groups.
====

By default, objects in the view pages are sorted based on event criticality. Objects with critical events are listed first, and objects with warning events are listed second. This provides an immediate visual indication of issues that must be addressed.

The controls along the top of the page enable you to select a particular view (for health, performance, capacity, and so on), perform searches to locate specific objects, create and apply filters to narrow the list of displayed data, add/remove/reorder columns on the page, and export the data on the page to a `.csv`, `.pdf`, or `.xlsx` file. After you have customized the page, you can save the results as a custom view and then schedule a report of this data to be generated and emailed on a regular basis.

You can assign performance threshold policies to, or clear threshold policies from, any object on the object inventory pages using the *Assign Performance Threshold Policy* and *Clear Performance Threshold Policy* buttons.

See xref:reference_port_performance_fields.adoc[Port performance fields] for descriptions of all the fields on this page.

*Related information*

xref:concept_refining_object_inventory_performance_page_content.adoc[Refining Performance inventory page contents]

xref:task_assigning_performance_threshold_policies_to_storage_objects.adoc[Assigning performance threshold policies to storage objects]

xref:task_removing_performance_threshold_policies_from_storage_objects.adoc[Removing performance threshold policies from storage objects]

xref:task_filtering_on_the_object_inventory_performance_pages.adoc[Filtering data in the Object Inventory Performance pages]

xref:task_exporting_storage_data_as_reports.adoc[Exporting storage data as reports]

xref:task_scheduling_a_report.adoc[Scheduling a report]
