---
permalink: online-help/reference-security-events.html
sidebar: sidebar
keywords: security events
summary: 'Security events provide you with information about the security status of ONTAP clusters, storage virtual machines \(SVMs\), and volumes based on parameters defined in the NetApp Security Hardening Guide for ONTAP 9. These events notify you of potential issues so that you can evaluate their severity and fix the issue if necessary.'
---
= Security events
:icons: font
:imagesdir: ../media/

[.lead]
Security events provide you with information about the security status of ONTAP clusters, storage virtual machines (SVMs), and volumes based on parameters defined in the _NetApp Security Hardening Guide for ONTAP 9_. These events notify you of potential issues so that you can evaluate their severity and fix the issue if necessary.

Security events are grouped by source type and include the event and trap name, impact level, and severity. These events appear in the cluster and storage VM event categories.

*Related information*

xref:concept-managing-cluster-security-objectives.adoc[Managing cluster security objectives]

xref:reference-cluster-events.adoc[Cluster events]

xref:reference-storage-vm-events.adoc[Storage VM events]
