---
permalink: online-help/reference_volume_capacity_fields.html
sidebar: sidebar
keywords: 
summary: 'The following fields are available in the Capacity: All Volumes view and can be used in custom views and in reports.'
---
= Volume capacity fields
:icons: font
:imagesdir: ../media/

[.lead]
The following fields are available in the Capacity: All Volumes view and can be used in custom views and in reports.

* *Volume*
+
The volume name.

* *Daily Growth Rate %*
+
The growth rate that occurs every 24 hours in the volume.

* *Days To Full*
+
The estimated number of days remaining before the volume reaches full capacity.

* *Available Data %*
+
The available data capacity in a volume as a percentage.

* *Available Data Capacity*
+
The available data capacity in a volume.

* *Used Data %*
+
The used data in a volume as a percentage.

* *Used Data Capacity*
+
The used data capacity in a volume.

* *Total Data Capacity*
+
The total data capacity (used plus available) in a volume.

* *Logical Space Used*
+
The logical space used by data in this volume without applying the savings from using ONTAP storage efficiency technologies.

* *Snapshot Overflow %*
+
The percentage of the data space that is consumed by Snapshot copies.

* *Snapshot Reserve Available %*
+
The amount of space available for Snapshot copies in the volume as a percentage.

* *Snapshot Reserve Available Capacity*
+
The amount of space available for Snapshot copies in the volume.

* *Snapshot Reserve Used %*
+
The amount of space used by Snapshot copies in the volume as a percentage.

* *Snapshot Reserve Used Capacity*
+
The amount of space used by Snapshot copies in the volume.

* *Snapshot Reserve Total Capacity*
+
Displays the total Snapshot copy capacity in the volume.

* *Quota Committed Capacity*
+
The space reserved for quotas in the volume.

* *Quota Overcommitted Capacity*
+
The amount of space that can be used for quotas before the system generates the Volume Quota Overcommitted event.

* *Total Number Of Inodes*
+
The number of inodes in the volume.

* *Inode Utilization %*
+
The percentage of inode space used in the volume.

* *Thin Provisioned*
+
Whether space guarantee is set for the selected volume. Valid values are Yes and No.

* *Space Guarantee*
+
The storage guarantee option that is associated with the volume.

* *Autogrow*
+
Whether the volume automatically grows in size when it is out of space.

* *Snapshot Autodelete*
+
Whether automatic deletion of Snapshot copies is enabled or disabled.

* *Deduplication*
+
Whether deduplication is enabled or disabled for the volume.

* *Compression*
+
Whether compression is enabled or disabled for the volume.

* *State*
+
The state of the volume that is being exported.

* *Protection Role*
+
The protection role that is set for the volume.

* *SnapLock Type*
+
Whether the volume is a SnapLock or non-SnapLock volume.

* *SnapLock Expiry Date*
+
The SnapLock expiration date.

* *Tiering Policy*
+
The tiering policy set for the volume. Valid when deployed on FabricPool-enabled aggregates only.

* *Caching Policy*
+
The caching policy that is associated with the selected volume.
+
The policy provides information about how Flash Pool caching occurs for the volume. See the Health: All Volumes view for more information on caching policies.

* *Cache Retention Priority*
+
The priority used for retaining cached pools.

* *Storage VM*
+
The name of the storage virtual machine (SVM) that contains the volume.

* *Cluster*
+
The name of the cluster on which the volume resides. You can click the cluster name to navigate to that cluster's health details page.

* *Cluster FQDN*
+
The fully qualified domain name (FQDN) of the cluster.
