---
permalink: online-help/reference_capacity_all_qtrees_view.html
sidebar: sidebar
keywords: 
summary: 'The Capacity: All Qtrees view enables you to view information about the capacity and utilization of qtrees in all clusters. This information enables you to understand possible capacity risks and also to view the configured and used disk percentage and number of files.'
---
= Capacity: All Qtrees view
:icons: font
:imagesdir: ../media/

[.lead]
The Capacity: All Qtrees view enables you to view information about the capacity and utilization of qtrees in all clusters. This information enables you to understand possible capacity risks and also to view the configured and used disk percentage and number of files.

By default, objects in the view pages are sorted based on event criticality. Objects with critical events are listed first, and objects with warning events are listed second. This provides an immediate visual indication of issues that must be addressed.

The controls along the top of the page enable you to select a particular view (for health, performance, capacity, and so on), perform searches to locate specific objects, create and apply filters to narrow the list of displayed data, add/remove/reorder columns on the page, and export the data on the page to a `.csv`, `.pdf`, or `.xlsx` file. After you have customized the page, you can save the results as a custom view and then schedule a report of this data to be generated and emailed on a regular basis.

You can customize capacity threshold settings for one or more qtrees by using the *Edit Threshold* button.

See xref:reference_qtree_capacity_fields.adoc[Qtree capacity fields] for descriptions of all the fields on this page.

*Related information*

xref:task_editing_individual_qtree_health_threshold_settings.adoc[Editing individual qtree health threshold settings]

xref:task_exporting_storage_data_as_reports.adoc[Exporting storage data as reports]

xref:task_scheduling_a_report.adoc[Scheduling a report]
