---
permalink: online-help/reference_aggregate_capacity_fields.html
sidebar: sidebar
keywords: 
summary: 'The following fields are available in the Aggregate Capacity and Utilization report and can be used in custom views and in reports.'
---
= Aggregate capacity fields
:icons: font
:imagesdir: ../media/

[.lead]
The following fields are available in the Aggregate Capacity and Utilization report and can be used in custom views and in reports.

* *Aggregate*
+
The aggregate name.

* *Daily Growth Rate %*
+
The growth rate that occurs every 24 hours in the aggregate.

* *Days To Full*
+
The estimated number of days remaining before the aggregate reaches full capacity.

* *Overcommitted Capacity %*
+
The aggregate overcommitment as a percentage.

* *Available Data %*
+
The available data capacity as a percentage.

* *Available Data Capacity*
+
The available data capacity.

* *Used Data %*
+
The used data capacity as a percentage.

* *Used Data Capacity*
+
The used data capacity.

* *Total Data Capacity*
+
The total data capacity (used plus available).

* *Logical Space Used*
+
The real size of the data that is being stored on the aggregate without applying the savings from using ONTAP storage efficiency technologies.

* *Snapshot Reserve Available %*
+
The amount of space available for Snapshot copies as a percentage.

* *Snapshot Reserve Available Capacity*
+
The amount of space available for Snapshot copies.

* *Snapshot Reserve Used %*
+
The amount of space used by Snapshot copies from the snapshot reserve as a percentage.

* *Snapshot Reserve Used Capacity*
+
The amount of space used by snapshot copies from the snapshot reserve.

* *Snapshot Reserve Total Capacity*
+
The total snapshot reserve capacity of the aggregate.

* *Cloud Tier Space Used*
+
The amount of data capacity that is currently being used in the cloud tier.

* *Cloud Tier*
+
The name of the cloud tier object store when it was created by ONTAP.

* *State*
+
The current state of the aggregate.

* *Type*
+
The aggregate type:

 ** HDD
 ** Hybrid
+
Combines HDDs and SSDs, but Flash Pool has not been enabled.

 ** Hybrid (Flash Pool)
+
Combines HDDs and SSDs, and Flash Pool has been enabled.

 ** SSD
 ** SSD (FabricPool)
+
Combines SSDs and a cloud tier

 ** HDD (FabricPool)
+
Combines HDDs and a cloud tier

 ** VMDisk (SDS)
+
Virtual disks within a virtual machine

 ** VMDisk (FabricPool)
+
Combines virtual disks and a cloud tier

 ** LUN (FlexArray)

* *RAID Type*
+
The RAID configuration type.

* *SnapLock Type*
+
The aggregate SnapLock Type. The possible values are Compliance, Enterprise, Non-SnapLock.

* *HA Pair*
+
The HA pair value obtained by forming two nodes.

* *Node*
+
The name of the node that contains the aggregate.

* *Cluster*
+
The cluster name. You can click the cluster name to navigate to that cluster's capacity details page.

* *Cluster FQDN*
+
The fully qualified domain name (FQDN) of the cluster.
