---
permalink: online-help/reference-performance-all-svms-view.html
sidebar: sidebar
keywords: 
summary: 'The Performance: All Storage VMs view displays an overview of the performance events, data, and configuration information for each storage virtual machine \(SVM\) that is being monitored by an instance of Unified Manager. This enables you to quickly monitor the performance of your SVMs, and to troubleshoot performance issues and threshold events.'
---
= Performance: All Storage VMs view
:icons: font
:imagesdir: ../media/

[.lead]
The Performance: All Storage VMs view displays an overview of the performance events, data, and configuration information for each storage virtual machine (SVM) that is being monitored by an instance of Unified Manager. This enables you to quickly monitor the performance of your SVMs, and to troubleshoot performance issues and threshold events.

By default, objects in the view pages are sorted based on event criticality. Objects with critical events are listed first, and objects with warning events are listed second. This provides an immediate visual indication of issues that must be addressed.

The controls along the top of the page enable you to select a particular view (for health, performance, capacity, and so on), perform searches to locate specific objects, create and apply filters to narrow the list of displayed data, add/remove/reorder columns on the page, and export the data on the page to a `.csv`, `.pdf`, or `.xlsx` file. After you have customized the page, you can save the results as a custom view and then schedule a report of this data to be generated and emailed on a regular basis.

You can assign performance threshold policies to, or clear threshold policies from, any object on the object inventory pages using the *Assign Performance Threshold Policy* and *Clear Performance Threshold Policy* buttons.

[NOTE]
====
The SVMs that are listed on this page include only Data and Cluster SVMs. Unified Manager does not use or display Admin or Node SVMs.
====

See xref:reference-svm-performance-fields.adoc[SVM performance fields] for descriptions of all the fields on this page.

*Related information*

xref:concept-refining-object-inventory-performance-page-content.adoc[Refining Performance inventory page contents]

xref:task-assigning-performance-threshold-policies-to-storage-objects.adoc[Assigning performance threshold policies to storage objects]

xref:task-removing-performance-threshold-policies-from-storage-objects.adoc[Removing performance threshold policies from storage objects]

xref:task-filtering-on-the-object-inventory-performance-pages.adoc[Filtering data in the Object Inventory Performance pages]

xref:task-exporting-storage-data-as-reports.adoc[Exporting storage data as reports]

xref:task-scheduling-a-report.adoc[Scheduling a report]
