---
permalink: online-help/reference_capacity_all_aggregates_view.html
sidebar: sidebar
keywords: 
summary: 'The Capacity: All Aggregates view enables you to view information about the capacity and utilization of aggregates in all clusters. This information enables you to understand possible capacity risks and also to view the configured, used, and unused capacity of aggregates.'
---
= Capacity: All Aggregates view
:icons: font
:imagesdir: ../media/

[.lead]
The Capacity: All Aggregates view enables you to view information about the capacity and utilization of aggregates in all clusters. This information enables you to understand possible capacity risks and also to view the configured, used, and unused capacity of aggregates.

The controls along the top of the page enable you to select a particular view (for health, performance, capacity, and so on), perform searches to locate specific objects, create and apply filters to narrow the list of displayed data, add/remove/reorder columns on the page, and export the data on the page to a `.csv`, `.pdf`, or `.xlsx` file. After you have customized the page, you can save the results as a custom view and then schedule a report of this data to be generated and emailed on a regular basis.

See xref:reference_aggregate_capacity_fields.adoc[Aggregate capacity fields] for descriptions of all the fields on this page.

*Related information*

xref:task_viewing_the_aggregate_list_and_details.adoc[Viewing the aggregate list and details]

xref:task_exporting_storage_data_as_reports.adoc[Exporting storage data as reports]

xref:task_scheduling_a_report.adoc[Scheduling a report]

xref:task_editing_individual_aggregate_health_threshold_settings.adoc[Editing individual aggregate health threshold settings]
