---
permalink: online-help/reference-health-all-aggregates-view.html
sidebar: sidebar
keywords: 
summary: 'The Health: All Aggregates view displays information about the aggregates that are monitored, and enables you to view and modify the threshold settings.'
---
= Health: All Aggregates view
:icons: font
:imagesdir: ../media/

[.lead]
The Health: All Aggregates view displays information about the aggregates that are monitored, and enables you to view and modify the threshold settings.

By default, objects in the view pages are sorted based on event criticality. Objects with critical events are listed first, and objects with warning events are listed second. This provides an immediate visual indication of issues that must be addressed. Each aggregate in the Aggregates grid has links to ONTAP System Manager. This link redirects you to view the same protection relationship in ONTAP System Manager.

The controls along the top of the page enable you to select a particular view (for health, performance, capacity, and so on), perform searches to locate specific objects, create and apply filters to narrow the list of displayed data, add/remove/reorder columns on the page, and export the data on the page to a `.csv`, `.pdf`, or `.xlsx` file. After you have customized the page, you can save the results as a custom view and then schedule a report of this data to be generated and emailed on a regular basis.

You can customize capacity threshold settings for one or more aggregates by using the *Edit Threshold* button.

See xref:reference-aggregate-health-fields.adoc[Aggregate health fields] for descriptions of all the fields on this page.
