---
permalink: online-help/task_viewing_the_cluster_list_and_details.html
sidebar: sidebar
keywords: 
summary: 'You can use the Health: All Clusters view to view your inventory of clusters. The Capacity: All Clusters view enables you to view summarized information about storage capacity and utilization in all clusters.'
---
= Viewing the cluster list and details
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Health: All Clusters view to view your inventory of clusters. The Capacity: All Clusters view enables you to view summarized information about storage capacity and utilization in all clusters.

== Before you begin

You must have the Operator, Application Administrator, or Storage Administrator role.

== About this task

You can also view details for individual clusters such as the cluster health, capacity, configuration, LIFs, nodes, and disks in that cluster by using the Cluster / Health details page.

The details in the Health: All Clusters view, Capacity: All Clusters view, and the Cluster / Health details page help you plan your storage. For example, before provisioning a new aggregate, you can select a specific cluster from the Health: All Clusters view and obtain capacity details to determine if the cluster has the required space.

== Steps

. In the left navigation pane, click *Storage* > *Clusters*.
. In the *View* menu, select *Health: All Clusters* view to view health information, or *Capacity: All Clusters* view to view details about storage capacity and utilization in all clusters.
. Click the name of a cluster to view complete details of the cluster in the *Cluster / Health* details page.

*Related information*

xref:reference_capacity_all_clusters_view.adoc[Capacity: All Clusters view]

xref:task_adding_users.adoc[Adding users]

xref:task_exporting_storage_data_as_reports.adoc[Exporting storage data as reports]

xref:task_adding_alerts.adoc[Adding alerts]

xref:task_editing_clusters.adoc[Editing clusters]

xref:reference_health_all_clusters_view.adoc[Health: All Clusters view]

xref:reference_health_cluster_details_page.adoc[Cluster / Health details page]
