---
permalink: online-help/task-viewing-the-node-list-and-details.html
sidebar: sidebar
keywords: 
summary: 'You can use the Health: All Nodes view to view the list of nodes in your clusters. You can use the Cluster / Health details page to view detailed information about nodes that are part of the cluster that is monitored.'
---
= Viewing the node list and details
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Health: All Nodes view to view the list of nodes in your clusters. You can use the Cluster / Health details page to view detailed information about nodes that are part of the cluster that is monitored.

== Before you begin

You must have the Operator, Application Administrator, or Storage Administrator role.

== About this task

You can view details such as the node state, cluster that contains the node, aggregate capacity details (used and total), and raw capacity details (usable, spare, and total). You can also obtain information about HA pairs, disks shelves, and ports.

== Steps

. In the left navigation pane, click *Storage* > *Nodes*.
. On the *Health: All Nodes* view, click the node whose details you want to view.
+
The detailed information for the selected node is displayed in the Cluster / Health details page. The left pane displays the list of HA pairs. By default, the HA Details is open, which displays HA state details and events related to the selected HA pair.

. To view other details about the node, perform the appropriate action:
+
|===
| To view...| Click...
a|
Details about the disk shelves
a|
*Disk Shelves*.
a|
Port-related information
a|
*Ports*.
|===

*Related information*

xref:task-adding-users.adoc[Adding users]

xref:task-viewing-the-cluster-list-and-details.adoc[Viewing the cluster list and details]

xref:task-exporting-storage-data-as-reports.adoc[Exporting storage data as reports]

xref:task-adding-alerts.adoc[Adding alerts]

xref:task-generating-a-hardware-inventory-report-for-contract-renewal.adoc[Generating a hardware inventory report for contract renewal]

xref:reference-health-all-nodes-view.adoc[Health: All Nodes view]
