---
permalink: online-help/task_viewing_the_svm_list_and_details.html
sidebar: sidebar
keywords: 
summary: 'From the Health: All Storage VMs view, you can monitor your inventory of storage virtual machines \(SVMs\). You can use the Storage VM / Health details page to view detailed information about SVMs that are monitored.'
---
= Viewing the Storage VM list and details
:icons: font
:imagesdir: ../media/

[.lead]
From the Health: All Storage VMs view, you can monitor your inventory of storage virtual machines (SVMs). You can use the Storage VM / Health details page to view detailed information about SVMs that are monitored.

== Before you begin

You must have the Operator, Application Administrator, or Storage Administrator role.

== About this task

You can view SVM details, such as the capacity, efficiency, and configuration of an SVM. You can also view information about the related devices and related alerts for that SVM.

== Steps

. In the left navigation pane, click *Storage* > *Storage VMs*.
. Choose one of the following ways to view the SVM details:
 ** To view information about the health of all SVMs in all clusters, in the View menu, select Health: All Storage VMs view.
 ** To view the complete details, click the Storage VM name.
+
You can also view the complete details by clicking *View Details* in the minimal details dialog box.
. View the objects related to the SVM by clicking *View Related* in the minimal details dialog box.

*Related information*

xref:task_adding_users.adoc[Adding users]

xref:task_exporting_storage_data_as_reports.adoc[Exporting storage data as reports]

xref:task_adding_alerts.adoc[Adding alerts]

xref:reference_health_all_svms_view.adoc[Health: All Storage VMs view]

xref:reference_health_svm_details_page.adoc[Storage VM / Health details page]
