---
permalink: online-help/task-downloading-an-https-certificate-signing-request-ocf.html
sidebar: sidebar
keywords: 
summary: 'You can download a certification signing request for the current HTTPS security certificate so that you can provide the file to a Certificate Authority to sign. A CA-signed certificate helps prevent man-in-the-middle attacks and provides better security protection than a self-signed certificate.'
---
= Downloading an HTTPS certificate signing request
:icons: font
:imagesdir: ../media/

[.lead]
You can download a certification signing request for the current HTTPS security certificate so that you can provide the file to a Certificate Authority to sign. A CA-signed certificate helps prevent man-in-the-middle attacks and provides better security protection than a self-signed certificate.

== Before you begin

You must have the Application Administrator role.

== Steps

. In the left navigation pane, click *General* > *HTTPS Certificate*.
. Click *Download HTTPS Certificate Signing Request*.
. Save the `<hostname>.csr` file.

== After you finish

You can provide the file to a Certificate Authority to sign, and then install the signed certificate.

*Related information*

xref:task-viewing-the-https-security-certificate-ocf.adoc[Viewing the HTTPS security certificate]

xref:task-generating-an-https-security-certificate-ocf.adoc[Generating an HTTPS security certificate]

xref:task-installing-a-ca-signed-and-returned-https-certificate.adoc[Installing a CA signed and returned HTTPS certificate]
