---
permalink: online-help/task-viewing-the-https-security-certificate-ocf.html
sidebar: sidebar
keywords: 
summary: 'You can compare the HTTPS certificate details to the retrieved certificate in your browser to ensure that your browser’s encrypted connection to Unified Manager is not being intercepted.'
---
= Viewing the HTTPS security certificate
:icons: font
:imagesdir: ../media/

[.lead]
You can compare the HTTPS certificate details to the retrieved certificate in your browser to ensure that your browser's encrypted connection to Unified Manager is not being intercepted.

== Before you begin

You must have the Operator, Application Administrator, or Storage Administrator role.

== About this task

Viewing the certificate enables you to verify the content of a regenerated certificate, or to view Subject Alt Names (SAN) from which you can access Unified Manager.

== Steps

. In the left navigation pane, click *General* > *HTTPS Certificate*.
+
The HTTPS certificate is displayed at the top of the page

== After you finish

If you need to view more detailed information about the security certificate than what is displayed on the HTTPS Certificate page, you can view the connection certificate in your browser.

*Related information*

xref:task-generating-an-https-security-certificate-ocf.adoc[Generating an HTTPS security certificate]

xref:task-downloading-an-https-certificate-signing-request-ocf.adoc[Downloading an HTTPS certificate signing request]

xref:task-installing-a-ca-signed-and-returned-https-certificate.adoc[Installing a CA signed and returned HTTPS certificate]
