---
settings:
  name: Active IQ Unified Manager 9.9
  downlevel: true 
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
    - version-number: "9.9"
      url: /active-iq-unified-manager-99     
    - version-number: "9.8"
      url: /active-iq-unified-manager-98      
    - version-number: "9.7"
      url: /active-iq-unified-manager-97
sidebar:
  entries:
    - title: Active IQ Unified Manager 9.9 docs
      url: "/index.html"
    - title: Release notes
      url: "/release-notes.html"
    - title: Get started
      entries:   
      - title: Quick start install for VMware vSphere
        url: "/qsg-vapp.html"
      - title: Quick start install for Linux
        url: "/qsg-linux.html"
      - title: Quick start install for Windows
        url: "/qsg-windows.html"
     
    - section: install-vapp
    - section: install-linux
    - section: install-windows
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - section: data-protection
    - section: reporting
    - section: api-automation
    - title: Legal notices
      url: "/legal-notices.html"
      