---
permalink: reporting/generaltask-um-rest-apis-that-can-be-used-for-reporting.html
sidebar: sidebar
keywords: 
summary: 'You can use REST APIs to help manage your clusters by viewing the health, capacity, performance, and security information captured by Unified Manager.'
---
= Unified Manager REST APIs that can be used for reporting
:icons: font
:imagesdir: ../media/

[.lead]
You can use REST APIs to help manage your clusters by viewing the health, capacity, performance, and security information captured by Unified Manager.

REST APIs are exposed through the Swagger web page. You can access the Swagger web page to display the Unified Manager REST API documentation, as well as to manually issue an API call. From the Unified Manager web UI, in the Menu Bar, click the *Help* button and then select *API Documentation*. For information about Unified Manager REST APIs, see link:../api-automation/concept-getting-started-with-getting-started-with-um-apis.html[Getting started with Active IQ Unified Manager].

You must have the Operator, Storage Administrator, or Application Administrator role to access the REST APIs.
