---
permalink: install-windows/task-upgrading-openjdk-on-windows-ocum.html
sidebar: sidebar
keywords: OpenJDK,JRE
summary: 'You can upgrade to a newer version of OpenJDK on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities.'
---
= Upgrading OpenJDK
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade to a newer version of OpenJDK on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities.

== Before you begin

You must have Windows admin privileges for the system on which Unified Manager is installed.

== About this task

You can update OpenJDK releases within release families. For example, you can upgrade from OpenJDK 11.0.7 to OpenJDK 11.0.9, but you cannot update directly from OpenJDK 11 to OpenJDK 12.

== Steps

. Log in as the admin user on the Unified Manager host machine.
. Download the appropriate version of OpenJDK (64-bit) from the OpenJDK site to the target system.
+
For example, download `openjdk-11_windows-x64_bin.zip` from `+http://jdk.java.net/11/+`.

. Use the Windows Services console to stop the following Unified Manager services:
 ** NetApp Active IQ Acquisition Service (Ocie-au)
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
. Expand the `zip` file.
. Copy the directories and files from the resulting `jdk` directory (for example, `jdk-11.0.9` to the location where Java is installed. Example: `C:\Program Files\NetApp\JDK\`
. Start the Unified Manager services by using the Windows Services console:
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
 ** NetApp Active IQ Acquisition Service (Ocie-au)
